server:
  port: 8080

spring:
  ai:
    dashscope:
      api-key:
    alibaba:
      toolcalling:
        weather:
          enabled: true
          api-key:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key:
      chat:
        options:
          model: qwen-max-latest
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: root
    password: 123wang
    url: jdbc:mysql://127.0.0.1:3306/rag_project?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
minio:
  host: http://127.0.0.1:9000
  url: ${minio.host}/${minio.bucketName}
  access-Key: minioadmin
  secret-Key: minioadmin
  bucketName: rag-project
# Redis
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml