version: '3.8'

services:
  # 文件存储器
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: minio
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - /data/docker/minio/data:/data
      - /data/docker/minio/config:/root/.minio/
    command: server /data --address ":8000" --console-address ":8001"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  pgdata:
